image: ubuntu

before_script:
  - apt-get update
  - apt-get --yes --force-yes install git ssh rsync

pages:
  stage: deploy
  script:
  - rsync -rltpP ./doc/ ./public/
  artifacts:
    paths:
    - public
  only:
  - master
