function c = rwb( n, signed )
%
% c = bgr( n=64, signed=false )
%
%   

    if nargin < 1, n = 64; end
    if nargin < 2, signed = false; end
    
    method = 'linear';
    w = [0.6,0.2,0.2,0.9];
    r = dk.clr.palette(0,w);
    b = dk.clr.palette(0.6,w);
    g = 0.9*[1 1 1];

    if signed
        if mod(n,2)==0, n=n+1; end
        C = [ ...
            -1.00, b.darkest; ...
            -0.65, b.normal; ...
            -0.45, b.lighter; ...
            -0.10, b.lightest; ...
            -0.00, g; ...
            +0.10, r.lightest; ...
            +0.45, r.lighter; ...
            +0.65, r.normal; ...
            +1.00, r.darkest ...
        ];
        x = linspace(-1,1,n)';
    else
        C = [ ...
            -0.00, g; ...
            +0.10, r.lightest; ...
            +0.45, r.lighter; ...
            +0.65, r.normal; ...
            +1.00, r.darkest  ...
        ];
        x = linspace(0,1,n)';
    end

    c = interp1( C(:,1), C(:,2:4), x, method );

end
